apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/MukeshPyatla/ecommerce-devops-pipeline'
    path: k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true